### ISSUE TITLE
Add tzdata package to Dockerfile

### ISSUE THREAD

**Issue by fabrizio-monaco** [Auhrus/fivem-docker-server#4]
**Describe your proposal as best you can.**
When i develop on the cfx server its important to make use of functions like os.date() or os.time(). Without this we are forced to use UTC Time which causes problems.
For this you could add the package "tzdata" to the Dockerfile so that we can set the timezone with the Environment Variable "TZ"

Example:

TZ=Europe/Berlin

**Is your request the result of a problem?**
Yes

**Additional Stuff (Screenhots, ...)**

**Comment by Auhrus** [comment]
Hi,
i want to keep the image as small as possible and only put the essentials for the server in it.
You can add two volumes in read only to have the server's time in the container (see below). Then it takes over the time and time zone from the operating system (Linux) itself.
```
-v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro
```
You can check whether the time has changed by executing the `date` command in the container.

**Comment by fabrizio-monaco** [comment]
Already tried this. Sadly didn't work for me. Could you check if you can find a solution and if not add the packacke? It's really not that big and is a standard practice if you want to change the timezone.

**Comment by Auhrus** [comment]
What you can do is download the [Dockerfile](https://github.com/Auhrus/fivem-docker-server/blob/999cbb13b393a8015c336771cb67ec42edd1629e/Dockerfile) and the [startup.sh](https://github.com/Auhrus/fivem-docker-server/blob/999cbb13b393a8015c336771cb67ec42edd1629e/startup.sh) from Github, and add the package itself to the Dockerfile in line 14. Then you can use docker build to build and use the package on your server. So you can add whatever you want.

**Comment by fabrizio-monaco** [comment]
Hey, sorry that I stick on this topic, but you should consider the following.

Of course, I can clone the project, but you must understand that your image is used in many different areas of the world. Many people will have this request if they want to dockerize with your image. You say that you only want to add essential packages to the image, and I get that. But **this is** indeed an **essential package** because os.time() and os.date() is unusable otherwise and must be manually counted up to the right timezone. In Database operations this is indispensable.

Would appreciate it if you would explain to me why this is not essential.

**Comment by Auhrus** [comment]
Hi, ok that's a valid point I've discovered it in a few docker containers I use (e.g. [docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) or [docker-webtop](https://github.com/linuxserver/docker-webtop)).
I will add it to the image but will do that tomorrow. I need some sleep first.🙂

**Comment by Auhrus** [comment]
Hi, I have just updated the package and adapted the documentation a bit.
ec718421a99d1670f58877f8f06ed8a6098025af
I hope you can continue your development now.
